### ISSUE TITLE
Handlebars dependency in SPA needs to be updated (security vulnerability )

### ISSUE THREAD

**Issue by nzthiago** [Azure-Samples/customer-car-reviews#12]
We need to update the `Handlebars` dependency in the SPA website, it needs to be > 4.0.0 due to a security vulnerability.

**Comment by TsuyoshiUshio** [comment]
Hi @nzthiago, 

I've create a pull request for this issue. 

https://github.com/Azure-Samples/customer-car-reviews/pull/13

**Comment by TsuyoshiUshio** [comment]
I hope this fix solve the warning.

**Comment by nzthiago** [comment]
Thanks, that fixed it
